#include "scene/ImportedViewRetarget.h"
#include "app/DualWield.h"
#include <iostream>
scene::CastScene makeHands(bool halo){
    scene::CastScene s;const auto add=[&](std::string name,int parent,scene::Vec3 p){scene::Bone b;b.name=name;b.parent=parent;b.restLocal.position=p;b.restGlobal=parent<0?scene::translation(p):s.skeleton.bones[parent].restGlobal*scene::translation(p);b.inverseBind=scene::inverseAffine(b.restGlobal);const auto i=s.skeleton.bones.size();s.skeleton.boneByName[name]=i;s.skeleton.bones.push_back(b);return static_cast<int>(i);};
    for(int side=0;side<2;++side){const std::string c=side?"ri":"le",h=side?"r":"l";
        const auto shoulder=add(halo?h+"_upperarm":"j_shoulder_"+c,-1,{0,float(side?8:-8),0});const auto elbow=add(halo?h+"_forearm":"j_elbow_"+c,shoulder,{10,0,0});const auto wrist=add(halo?h+"_hand":"j_wrist_"+c,elbow,{10,0,0});
        int f=0;for(const std::string finger:{"thumb","index","middle","ring","pinky"}){int parent=wrist;for(int j=0;j<3;++j){const auto name=halo?h+"_"+finger+"_"+(j==0?"low":j==1?"mid":"tip"):"j_"+(finger=="middle"?"mid":finger)+"_"+c+"_"+std::to_string(j);parent=add(name,parent,j?scene::Vec3{2,0,0}:scene::Vec3{4,float(f-2),float(f==0?2:0)});}++f;}
        scene::Mesh mesh;for(int j=0;j<3;++j){scene::Vertex v;v.position={float(20+j),float(side?8:-8),0};v.bones[0]=wrist;v.uv={.2f*j,.75f};mesh.vertices.push_back(v);}mesh.indices={0,1,2};s.meshes.push_back(mesh);
    }return s;
}
int main(){int failures{};const auto check=[&](bool ok,const char* msg){if(!ok){++failures;std::cerr<<msg<<'\n';}};
    {scene::CastScene skin;scene::Bone b;b.name="cs_hand_CSO2_MHAND L ForeTwist1";skin.skeleton.bones.push_back(b);scene::Mesh m;m.name="weapon/forearm";m.viewmodelWeapon=true;m.vertices.resize(3);for(auto& v:m.vertices){v.bones={};v.weights={1,0,0,0};}m.indices={0,1,2};skin.meshes.push_back(m);scene::imported::retainExplicitHandMeshes(skin);check(!skin.meshes[0].viewmodelWeapon,"universal twist-weighted sleeve classified as weapon");skin.skeleton.bones[0].name="cs_weapon_fixture_gun";scene::imported::retainExplicitHandMeshes(skin);check(skin.meshes[0].viewmodelWeapon,"weapon bones classified as shared hands");}
    {scene::CastScene skin;scene::Bone palm;palm.name="cs_hand_L.palm";skin.skeleton.bones.push_back(palm);scene::Bone twist;twist.name="cs_hand_CSO2_MHAND L ForeTwist1";skin.skeleton.bones.push_back(twist);scene::Mesh hand;hand.name="hands/glove";hand.vertices.resize(3);hand.indices={0,1,2};for(auto& v:hand.vertices){v.bones={};v.weights={1,0,0,0};}auto sleeve=hand;sleeve.name="weapon/sleeve";for(auto& v:sleeve.vertices)v.bones[0]=1;skin.meshes={hand,sleeve};scene::imported::retainExplicitHandMeshes(skin);check(skin.meshes.size()==2&&skin.meshes[1].indices.size()==3&&!skin.meshes[1].viewmodelWeapon,"flat universal helper triangles lost beside explicit glove mesh");}
    for(const auto game:{"cs1.6","css","csnz","cso2"})check(assets::imported::role(game,"hands_shared")==assets::Role::ViewHands,"universal viewhands not classified");
    {auto driver=makeHands(false);const auto original=driver.skeleton.bones;driver.skeleton.boneByName.clear();for(size_t i=0;i<original.size();++i){auto& b=driver.skeleton.bones[i];b.name=i<18?"cs_hand_Left_H_Bone"+std::to_string(i+20):"unrelated_"+std::to_string(i);b.parent=-1;driver.skeleton.boneByName[b.name]=i;}for(size_t i=0;i<18;++i){auto b=original[i];b.name="cs_weapon_fixture_"+driver.skeleton.bones[i].name.substr(8);if(b.parent>=0)b.parent+=static_cast<int>(original.size());driver.skeleton.boneByName[b.name]=driver.skeleton.bones.size();driver.skeleton.bones.push_back(b);}const auto layout=scene::imported::viewLayout(driver);check(layout.usable()&&layout.arms[0].valid()&&!layout.arms[1].valid(),"flat one-arm hierarchy not recovered");driver.meshes.clear();std::string error;check(scene::imported::fitForeignViewSkin(driver,makeHands(true),error),"foreign hand cannot fit flat one-arm driver");check(driver.meshes.size()==1,"unauthored offhand was grafted onto one-arm driver");check(driver.skeleton.bones[2].parent==-1,"anatomy discovery modified animated hierarchy");}
    {auto universal=makeHands(false);universal.skeleton.boneByName.clear();for(int side=0;side<2;++side){const auto base=side*18;const std::string p=std::string("cs_hand_")+(side?"R.":"L.");universal.skeleton.bones[base+1].name=p+"forearm";universal.skeleton.bones[base+2].name=p+"palm";for(int f=0;f<5;++f)for(int j=0;j<3;++j)universal.skeleton.bones[base+3+f*3+j].name=p+"finger"+std::to_string(f)+"."+std::to_string(j);}for(size_t i=0;i<universal.skeleton.bones.size();++i)universal.skeleton.boneByName[universal.skeleton.bones[i].name]=i;check(scene::imported::viewLayout(universal).valid(),"universal CS anatomy missing");auto driver=makeHands(true);std::string error;check(scene::imported::fitForeignViewSkin(driver,universal,error),"universal CS skin cannot fit Halo driver");}
    {scene::CastScene s;const std::string prefix="magnum_1_fp_0_2_dual_first_person_dual_";for(const auto name:{"idle_var1__left_3","idle_var1__right_3","fire_1_var1__left_0","fire_1_var1__right_0"}){scene::Animation a;a.sourceName=prefix+name+".cast";a.tracks.resize(1);s.animations.push_back(a);}check(cadence::dual::sideClip(s,prefix,"idle",0,false)==1,"Halo right idle selection");check(cadence::dual::sideClip(s,prefix,"fire",1,false)==2,"Halo left fire selection");check(assets::imported::matchesAnimation("eldewrito","magnum_1_fp_0_2_dual_weapon",prefix+"idle_var1__left_3.cast"),"Halo dual catalog discovery");}
    for(bool reverse:{false,true}){auto driver=makeHands(reverse),skin=makeHands(!reverse);const auto bind=driver.skeleton.bones;scene::Mesh weapon;weapon.name="mechanism";weapon.viewmodelWeapon=true;driver.meshes.push_back(weapon);std::string error;
        check(scene::imported::fitForeignViewSkin(driver,skin,error),error.c_str());check(driver.skeleton.bones.size()==bind.size(),"driver bone count changed");for(std::size_t i=0;i<bind.size();++i)check(driver.skeleton.bones[i].restGlobal.v==bind[i].restGlobal.v,"driver bind changed");check(driver.meshes.size()==3&&driver.meshes[0].name=="mechanism","weapon geometry removed");check(driver.meshes.back().vertices[2].uv.x==.4f,"UV changed");}
    auto driver=makeHands(false),incomplete=makeHands(true);incomplete.skeleton.boneByName.erase("l_thumb_low");const auto before=driver.meshes.size();std::string error;check(!scene::imported::fitForeignViewSkin(driver,incomplete,error)&&driver.meshes.size()==before,"incomplete anatomy modified driver");
    {auto four=makeHands(true);for(const auto* side:{"l","r"})for(const auto* joint:{"low","mid","tip"})four.skeleton.boneByName.erase(std::string(side)+"_middle_"+joint);
     check(scene::imported::viewLayout(four).valid(),"complete four-digit anatomy rejected");
     auto native=makeHands(false);const auto original=native.skeleton.bones;check(scene::imported::fitForeignViewSkin(native,four,error),"four-digit skin cannot bind five-digit driver");
     for(std::size_t i=0;i<original.size();++i)check(native.skeleton.bones[i].restGlobal.v==original[i].restGlobal.v,"four-digit fit changed driver bind");
     check(native.meshes.size()==four.meshes.size()&&native.meshes[0].indices==four.meshes[0].indices,"four-digit fitting discarded skin geometry");
     auto partial=makeHands(true);partial.skeleton.boneByName.erase("l_middle_low");check(!scene::imported::viewLayout(partial).usable(),"partial middle chain accepted as four-digit anatomy");
     auto sparse=four;sparse.skeleton.boneByName.erase("l_ring_low");sparse.skeleton.boneByName.erase("l_ring_mid");sparse.skeleton.boneByName.erase("l_ring_tip");check(!scene::imported::viewLayout(sparse).usable(),"unsupported three-digit anatomy accepted");
     const auto oldMeshes=four.meshes.size();check(!scene::imported::fitForeignViewSkin(four,makeHands(false),error)&&four.meshes.size()==oldMeshes,"missing driver digit silently collapsed or mutated output");
     check(error.find("lacks a digit")!=std::string::npos,"missing driver digit diagnosis absent");}
    for(bool pb:{false,true}){auto native=makeHands(false);native.pointBlankNativeCentimetres=pb;native.codmNativeCentimetres=!pb;check(scene::imported::fitForeignViewSkin(native,makeHands(true),error),"native marker fixture fit failed");check(native.viewHandsDriverGame==(pb?"pointblank":"codm"),"native driver identity lost during foreign skin fit");}
    {auto shared=makeHands(false);auto& rig=shared.skeleton;rig.boneByName.clear();
        for(std::size_t i=0;i<rig.bones.size();++i){auto& b=rig.bones[i];b.name=i==2?"Bone_Lefthand":i==20?"Bone_Righthand":"Bone"+std::to_string(i);rig.boneByName[b.name]=i;}
        // The second arm shares the first arm's top-level root, as in CSNZ.
        rig.bones[18].parent=0;
        const auto layout=scene::imported::viewLayout(shared);
        check(layout.valid()&&layout.arms[0].wrist==2&&layout.arms[1].wrist==20,"named wrists sharing one root not recognized");
        check(scene::imported::fitForeignViewSkin(shared,makeHands(true),error),"shared-root native hand fit failed");
    }
    {auto source=makeHands(true),target=makeHands(false);const int finger=6;auto bridge=source.skeleton.bones[finger];bridge.name="unnamed coincident bridge";const auto index=source.skeleton.bones.size();source.skeleton.bones.push_back(bridge);source.skeleton.bones[finger].parent=static_cast<int>(index);for(auto& v:source.meshes[0].vertices){v.bones[0]=static_cast<uint32_t>(index);v.weights={1,0,0,0};}check(scene::imported::fitForeignViewSkin(target,source,error),"coincident helper fit failed");check(target.meshes[0].vertices[0].bones[0]==finger,"coincident finger bridge mapped to wrist");}
    {auto source=makeHands(true),target=makeHands(false);auto twist=source.skeleton.bones[1];twist.name="CSO2_MHAND L ForeTwist1";twist.restGlobal=scene::translation({15,-8,0});twist.inverseBind=scene::inverseAffine(twist.restGlobal);const auto index=source.skeleton.bones.size();source.skeleton.bones.push_back(twist);for(auto& v:source.meshes[0].vertices){v.bones[0]=static_cast<uint32_t>(index);v.weights={1,0,0,0};}check(scene::imported::fitForeignViewSkin(target,source,error),"distributed twist fit failed");const auto& v=target.meshes[0].vertices[0];check(v.weights[0]>.49f&&v.weights[1]>.49f&&((v.bones[0]==1&&v.bones[1]==2)||(v.bones[0]==2&&v.bones[1]==1)),"forearm twist lost measured elbow/wrist distribution");}
    {auto source=makeHands(true),target=makeHands(false);for(auto& b:target.skeleton.bones)if(b.name.starts_with("j_index_")||b.name.starts_with("j_pinky_")){const float center=b.name.find("_le_")!=std::string::npos?-8.f:8.f;b.restGlobal.v[13]=center+(b.restGlobal.v[13]-center)*2.f;}for(auto& v:source.meshes[0].vertices){v.position={10,-7,0};v.bones={1,0,0,0};v.weights={1,0,0,0};}check(scene::imported::fitForeignViewSkin(target,source,error),"different palm proportion fit failed");check(std::abs(scene::length(target.meshes[0].vertices[0].position-scene::Vec3{10,-8,0})-1.f)<.001f,"palm width incorrectly inflates forearm");}
    {auto source=makeHands(false),target=makeHands(true);
        // A donor upper arm points up, while the shoulderless driver extends
        // horizontally. Its cap must continue behind the target elbow.
        for(int side=0;side<2;++side){const int base=side*18;auto& shoulder=source.skeleton.bones[base];shoulder.restGlobal=scene::translation({10,float(side?8:-8)+10,0});shoulder.inverseBind=scene::inverseAffine(shoulder.restGlobal);
            target.skeleton.boneByName.erase(side?"r_upperarm":"l_upperarm");
            auto& m=source.meshes[side];for(auto& v:m.vertices){v.position={10,float(side?8:-8)+10,0};v.bones={static_cast<uint32_t>(base),0,0,0};v.weights={1,0,0,0};}}
        const auto bind=target.skeleton.bones;check(scene::imported::fitForeignViewSkin(target,source,error),"shoulderless arm fit failed");
        for(int side=0;side<2;++side){const auto p=target.meshes[side].vertices[0].position;check(scene::length(p-scene::Vec3{0,float(side?8:-8),0})<.001f,"upper arm retains donor bend");}
        for(size_t i=0;i<bind.size();++i)check(bind[i].restGlobal.v==target.skeleton.bones[i].restGlobal.v,"straightening modified driver");}
    {auto source=makeHands(false),target=makeHands(true);for(auto& b:target.skeleton.bones){b.restGlobal.v[12]*=.25f;b.restGlobal.v[13]*=.25f;b.restGlobal.v[14]*=.25f;b.inverseBind=scene::inverseAffine(b.restGlobal);}
        for(int side=0;side<2;++side){const int base=side*18;target.skeleton.boneByName.erase(side?"r_upperarm":"l_upperarm");auto& shoulder=source.skeleton.bones[base];shoulder.restGlobal=scene::translation({10,float(side?8:-8)+10,0});shoulder.inverseBind=scene::inverseAffine(shoulder.restGlobal);
            for(auto& v:source.meshes[side].vertices){v.position={10,float(side?8:-8)+5,0};v.bones={static_cast<uint32_t>(base),static_cast<uint32_t>(base+1),0,0};v.weights={.5f,.5f,0,0};}}
        check(scene::imported::fitForeignViewSkin(target,source,error),"scaled straight sleeve fit failed");for(int side=0;side<2;++side)check(scene::length(target.meshes[side].vertices[0].position-scene::Vec3{1.25f,float(side?2:-2),0})<.001f,"scaled sleeve deviated from straight forearm");}
    {auto skin=makeHands(false),target=makeHands(true);skin.skeleton.boneByName.clear();
        for(int side=0;side<2;++side){const int base=side*18;const std::string p=std::string("cs_hand_")+(side?"R.":"L.");
            skin.skeleton.bones[base].name=p+"upperarm";skin.skeleton.bones[base+1].name=p+"forearm";skin.skeleton.bones[base+2].name=p+"palm";
            for(int f=0;f<5;++f)for(int j=0;j<3;++j)skin.skeleton.bones[base+3+f*3+j].name=p+"finger"+std::to_string(f)+"."+std::to_string(j);
            auto clavicle=skin.skeleton.bones[base];clavicle.name=p+"clavicle";const auto index=skin.skeleton.bones.size();skin.skeleton.bones.push_back(clavicle);
            for(auto& v:skin.meshes[side].vertices){v.bones={static_cast<uint32_t>(base),static_cast<uint32_t>(index),0,0};v.weights={.5f,.5f,0,0};}
        }
        for(size_t i=0;i<skin.skeleton.bones.size();++i){auto& b=skin.skeleton.bones[i];b.parent=-1;skin.skeleton.boneByName[b.name]=i;}
        check(scene::imported::viewLayout(skin).arms[0].shoulder==0,"universal upper arm missing");
        check(scene::imported::fitForeignViewSkin(target,skin,error),"flat universal upper-arm/clavicle fit failed");
        check(target.meshes.size()==2&&target.meshes[0].indices.size()==3&&target.meshes[1].indices.size()==3,"universal sleeve triangles discarded");
    }
    return failures?1:0;}
