#include "assets/LocalAssetPaths.h"
#define main cadenceApplicationMain
#include "../src/app/main.cpp"
#undef main
int main(){
 if(!glfwInit())return 1;glfwWindowHint(GLFW_VISIBLE,GLFW_FALSE);auto*w=glfwCreateWindow(900,700,"v202 verification",nullptr,nullptr);if(!w)return 2;glfwMakeContextCurrent(w);
 ImGui::CreateContext();ImGui::GetIO().IniFilename=nullptr;ImGui_ImplGlfw_InitForOpenGL(w,true);ImGui_ImplOpenGL3_Init("#version 330");
 auto state=std::make_unique<AppState>();auto&a=*state;a.window=w;a.deferSceneUpload=true;a.defaultSalukiDirectory=cadence::local_assets::exportPath("");std::string error;
 if(!a.renderer.initialize(error))return 3;std::filesystem::create_directories("diagnostics/v202");std::ofstream report("diagnostics/v202/results.txt");
 for(const auto*g:{"bo2","cs2","codm","mw","mwr","aw"})(void)assets::appendScan(a.defaultSalukiDirectory/g,g,a.assetCatalog,error);
 auto find=[&](std::string game,assets::Role role,std::string key){for(size_t i=0;i<a.assetCatalog.entries.size();++i){const auto&e=a.assetCatalog.entries[i];if(e.game==game&&e.role==role&&lowerText(e.name).find(lowerText(key))!=std::string::npos)return i;}throw std::runtime_error("Missing "+game+" "+key);};
 auto capture=[&](scene::CastScene& s,size_t clip,const std::string& name){if(!a.renderer.loadScene(s,error))throw std::runtime_error(error);a.renderer.setDebugView(1);for(int k=0;k<5;++k){const auto frame=s.animations[clip].durationFrames*k/4.f;auto pose=s.samplePose(clip,frame);if(s.animations[clip].action==scene::ActionRole::Fire){scene::AnimationQuery q;q.domain=scene::AnimationDomain::PlayerBody;q.motion=scene::MotionRole::Idle;q.stance=scene::Stance::Crouch;q.weapon=scene::WeaponClass::Rifle;if(auto base=scene::findBestAnimation(s,q)){auto local=s.sampleLocalPose(*base,0);scene::pointblank::overlayTorso(s,clip,frame,local);pose=s.globalPose(local);}}auto vp=scene::perspective(45*scene::kPi/180,1.3f,1,4000)*scene::lookAt({270,-290,175},{0,0,90},{0,0,1});a.renderer.render(s,pose,vp,900,700,false,false,false);if(!a.renderer.saveColorPng("diagnostics/v202/"+name+std::to_string(k)+".png",error))throw std::runtime_error(error);}};
 const auto mw=find("mw",assets::Role::PlayerModel,""),codm=find("codm",assets::Role::PlayerModel,"Ghost"),groza=find("codm",assets::Role::ViewWeapon,"groza");
 PointBlankPreparationBatch batch;
 for(auto body:{mw,codm}){a.classWorldModelAsset=body;auto actor=scene::buildScene(cast::Document::load(a.assetCatalog.entries[body].path));for(auto part:characterAssemblyParts(a,a.assetCatalog.entries[body]))scene::appendRigModel(cast::Document::load(a.assetCatalog.entries[part].path),actor,a.assetCatalog.entries[part].name);appendClassBodyAnimations(a,a.assetCatalog.entries[body].game,actor);report<<"BODY "<<a.assetCatalog.entries[body].name<<" clips="<<actor.animations.size()<<std::endl;
  scene::AnimationQuery q;q.domain=scene::AnimationDomain::PlayerTorso;q.action=scene::ActionRole::Fire;q.stance=scene::Stance::Crouch;q.weapon=scene::WeaponClass::Rifle;if(auto c=scene::findBestAnimation(actor,q)){report<<"CROUCH FIRE "<<actor.animations[*c].sourceName<<std::endl;capture(actor,*c,a.assetCatalog.entries[body].game+"_crouch");}
  if(body==mw)for(size_t ci=0;ci<actor.animations.size();++ci)if(actor.animations[ci].sourceName=="pt_crouch_shoot.cast"||actor.animations[ci].sourceName=="pt_crouch_rifle_fire_ads.cast"||actor.animations[ci].sourceName=="pt_crouch_shoot_ads.cast")capture(actor,ci,"compare_"+actor.animations[ci].sourceName);
  const auto wi=findWorldWeaponForViewWeapon(a,a.assetCatalog.entries[groza]);report<<"GROZA world="<<wi<<std::endl;if(wi<a.assetCatalog.entries.size())attachCodmWorldWeapon(a,cast::Document::load(a.assetCatalog.entries[wi].path),groza,actor);report<<"GROZA attachments="<<actor.attachments.size()<<std::endl;for(auto&s:actor.warnings)if(s.find("CODM world")!=std::string::npos)report<<s<<std::endl;
  if(actor.attachments.empty())return 5;
  q.domain=scene::AnimationDomain::PlayerBody;q.action=scene::ActionRole::None;q.motion=scene::MotionRole::Idle;q.stance=scene::Stance::Stand;if(auto c=scene::findBestAnimation(actor,q))capture(actor,*c,a.assetCatalog.entries[body].game+"_groza");
  if(body==mw){actor.attachments.clear();const auto gun=find("mwr",assets::Role::ViewWeapon,"de50_vm_camo");const auto world=findWorldWeaponForViewWeapon(a,a.assetCatalog.entries[gun]);scene::appendAttachment(cast::Document::load(a.assetCatalog.entries[world].path),actor,preferredAttachmentBone(actor.skeleton),"MWR de50");configureMwrWeaponOnCod4(a,actor,0,"mwr",weapon::Archetype::Pistol);q.weapon=scene::WeaponClass::Pistol;if(auto c=scene::findBestAnimation(actor,q)){capture(actor,*c,"mw_mwr_de50");report<<"MWR attach bone="<<actor.skeleton.bones[actor.attachments[0].boneIndex].name<<std::endl;}}
  if(body==mw){actor.attachments.clear();const auto gun=find("mwr",assets::Role::ViewWeapon,"wpn_h1_lmg_m60_vm_camo");const auto world=findWorldWeaponForViewWeapon(a,a.assetCatalog.entries[gun]);if(world>=a.assetCatalog.entries.size())return 9;scene::appendAttachment(cast::Document::load(a.assetCatalog.entries[world].path),actor,preferredAttachmentBone(actor.skeleton),"MWR m60");configureMwrWeaponOnCod4(a,actor,0,"mwr",weapon::Archetype::Lmg);q.weapon=scene::WeaponClass::Rifle;if(auto c=scene::findBestAnimation(actor,q))capture(actor,*c,"mw_mwr_m60");}
  appendSupplementalWorldMotion(a,actor);if(auto c=selectWorldBoost(actor,scene::WeaponClass::Rifle)){report<<"BOOST "<<a.assetCatalog.entries[body].game<<" adapter="<<bool(actor.animations[*c].coldWarWorldPose)<<std::endl;capture(actor,*c,a.assetCatalog.entries[body].game+"_boost");if(auto ad=actor.animations[*c].coldWarWorldPose){for(size_t i=0;i<actor.skeleton.bones.size();++i)if(actor.skeleton.bones[i].name.find("hip")!=std::string::npos||actor.skeleton.bones[i].name.find("knee")!=std::string::npos){report<<actor.skeleton.bones[i].name<<" -> "<<ad->sourceBones[i]<<std::endl;if((actor.skeleton.bones[i].name=="j_knee_le"||actor.skeleton.bones[i].name=="j_hip_le")&&ad->sourceBones[i]<0)return 7;}}}
 }
 for(const auto gun:{"deagle_model","ak47_model","awp_model","knife_m9_model"}){
 a.selectedBaseAsset=find("codm",assets::Role::ViewHands,"C_M_Ghost_1P");a.selectedWeaponAsset=find("cs2",assets::Role::ViewWeapon,gun);equipViewWeapon(a,a.selectedWeaponAsset,nullptr);report<<gun<<" CS2 driver="<<a.scene.viewHandsDriverGame<<" adapter="<<bool(a.scene.codmRigAdapter)<<" clips="<<a.scene.animations.size()<<" status="<<a.status<<std::endl;if(!a.scene.codmRigAdapter||a.scene.animations.empty())return 8;
 a.deferSceneUpload=false;a.showGrid=false;a.assetFirstPerson=true;a.viewmodelCamera=true;
 for(auto action:{"idle","fire","reload"})if(auto c=findViewmodelClip(a,action)){a.animationIndex=*c;a.animationFrame=a.scene.animations[*c].durationFrames*.5f;uploadMainScene(a);ImGui_ImplOpenGL3_NewFrame();ImGui_ImplGlfw_NewFrame();ImGui::NewFrame();ImGui::SetNextWindowPos({0,0});ImGui::SetNextWindowSize({900,700});ImGui::Begin("audit");drawViewport(a,880,660);ImGui::End();ImGui::Render();(void)a.renderer.saveColorPng(std::string("diagnostics/v202/cs2_")+gun+"_"+action+".png",error);}
 const auto bones=a.scene.skeleton.bones.size();take::ActorManifest manifest;manifest.baseModel=a.loadedBaseModelPath.string();for(const auto&p:a.loadedRigModelPaths)manifest.rigModels.push_back(p.string());if(!restoreTakeActor(a,manifest,bones,error)||!a.scene.codmRigAdapter){report<<"REPLAY FAIL "<<error<<std::endl;return 6;}report<<"CS2 replay PASS"<<std::endl;
 }
 return 0;
}
